# Describes the format for available component services

clear_cache:
  name: Clear the cache
  description: Clear the cache. Requires a restart.
  fields:
    entity_id:
      name: Entity
      description: Name(s) of homematic central to clear the cache.
      required: true
      selector:
        entity:
          domain: homematicip_local

delete_device:
  name: Delete a device
  description: Delete a device from HA.
  fields:
    device_id:
      name: Device
      description: Select a device
      required: true
      selector:
        device:
          domain: homematicip_local

export_device_definition:
  name: Export device definition
  description: Export a device definition to 'Your home-assistant config directory'/homematicip_local/export*
  fields:
    device_id:
      name: Device
      description: Select a device
      required: true
      selector:
        device:
          domain: homematicip_local

set_variable_value:
  name: Set variable value
  description: Set the name of a node.
  fields:
    entity_id:
      name: Entity
      description: Name(s) of homematic central to set value.
      required: true
      selector:
        entity:
          domain: homematicip_local
    name:
      name: Name
      description: Name of the variable to set.
      required: true
      example: "testvariable"
      selector:
        text:
    value:
      name: Value
      description: New value
      required: true
      example: 1
      selector:
        text:

set_device_value:
  name: Set device value
  description: Set a device property on RPC XML interface.
  fields:
    device_id:
      name: Device
      description: Select a device
      required: true
      selector:
        device:
          domain: homematicip_local
    channel:
      name: Channel
      description: Channel for calling a parameter.
      required: true
      selector:
        number:
          min: 1
          max: 99
    parameter:
      name: Parameter
      description: Event to send i.e. PRESS_LONG, PRESS_SHORT
      required: true
      example: PRESS_LONG
      selector:
        text:
    value:
      name: Value
      description: New value
      required: true
      example: 1
      selector:
        text:
    value_type:
      name: Value type
      description: Type for new value
      selector:
        select:
          options:
            - 'boolean'
            - 'dateTime.iso8601'
            - 'double'
            - 'int'
            - 'string'
    rx_mode:
      name: RX mode
      description: The receive mode used.
      example: BURST
      selector:
        text:

set_install_mode:
  name: Set install mode
  description: Set a RPC XML interface into installation mode.
  fields:
    interface_id:
      name: Interface
      description: Select the given interface into install mode
      required: true
      example: Interfaces name from config
      selector:
        text:
    mode:
      name: Mode
      description: 1= Normal mode / 2= Remove exists old links
      default: 1
      selector:
        number:
          min: 1
          max: 2
    time:
      name: Time
      description: Time to run in install mode
      default: 60
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    address:
      name: Address
      description: Address of homematic device or BidCoS-RF to learn
      example: LEQ3948571
      selector:
        text:

put_paramset:
  name: Put paramset
  description: Call to putParamset in the RPC XML interface
  fields:
    device_id:
      name: Device
      description: Select a device
      required: true
      selector:
        device:
          domain: homematicip_local
    channel:
      name: Channel
      description: Channel for calling a paramset.
      required: true
      selector:
        number:
          min: 1
          max: 99
    paramset_key:
      name: Paramset key
      description: The paramset_key argument to putParamset
      required: true
      example: MASTER
      selector:
        text:
    paramset:
      name: Paramset
      description: A paramset dictionary
      required: true
      example: '{"WEEK_PROGRAM_POINTER": 1}'
      selector:
        object:
    rx_mode:
      name: RX mode
      description: The receive mode used.
      example: BURST
      selector:
        text:

enable_away_mode_by_calendar:
  name: Enable climate away mode by calendar
  description: Enable climate away mode by calendar.
  target:
    entity:
      integration: homematicip_local
      domain: climate
  fields:
    end:
      name: End time
      description: The time when the away mode should automatically be disabled.
      required: true
      example: 2022-01-28 14:00
      selector:
        text:
    away_temperature:
      name: Set point temperature
      description: The temperature for the away mode.
      required: true
      default: 18.0
      selector:
        number:
          min: 4.5
          max: 30.5
          step: 0.5
          mode: slider

enable_away_mode_by_duration:
  name: Enable climate away mode by duration
  description: Enable climate away mode by duration.
  target:
    entity:
      integration: homematicip_local
      domain: climate
  fields:
    hours:
      name: Hours
      description: The number of hours after the away mode should automatically be disabled.
      required: true
      default: 6
      selector:
        number:
          min: 1
          max: 99
          step: 1
          mode: slider
    away_temperature:
      name: Set point temperature
      description: The temperature for the away mode.
      required: true
      default: 18.0
      selector:
        number:
          min: 4.5
          max: 30.5
          step: 0.5
          mode: slider

disable_away_mode:
  name: Disable climate away mode
  description: Disable climate away mode.
  target:
    entity:
      integration: homematicip_local
      domain: climate

turn_on_siren:
  description: Turn siren on.
  target:
    entity:
      domain: siren
  fields:
    tone:
      description: The tone to emit when turning the siren on.
      example: FREQUENCY_RISING
      required: false
      selector:
        text:
    light:
      description: The light to emit when turning the siren on.
      example: BLINKING_ALTERNATELY_REPEATING
      required: false
      selector:
        text:
    duration:
      description: The duration in seconds of the noise to emit when turning the siren on.
      example: 60
      required: false
      selector:
        text:
